/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontFamily: {
        mukta: ['Mukta_400Regular', 'system-ui', 'sans-serif'],
        'mukta-medium': ['Mukta_500Medium', 'system-ui', 'sans-serif'],
        'mukta-bold': ['Mukta_700Bold', 'system-ui', 'sans-serif'],
        inter: ['Inter_400Regular', 'system-ui', 'sans-serif'],
        'inter-medium': ['Inter_500Medium', 'system-ui', 'sans-serif'],
      },
      colors: {
        // Default (saffron) palette — bg-kc-bg, text-kc-primary, etc.
        kc: {
          bg: '#FBF7F0',
          surface: '#FFFFFF',
          'surface-warm': '#FBF1E3',
          'surface-warmer': '#F6E6CC',
          text: '#1C1917',
          'text-muted': '#6B5E52',
          'text-faint': '#A39687',
          border: '#EAE0D2',
          'border-soft': '#F2EADC',
          primary: '#B7531A',
          'primary-deep': '#7A2E0B',
          'primary-soft': '#F8E7D2',
          accent: '#7C2D12',
          success: '#15803D',
          'success-soft': '#DCFCE7',
          info: '#1E40AF',
          warn: '#A16207',
          'warn-soft': '#FEF3C7',
          error: '#B91C1C',
          'chip-bg': '#F4EBDD',
          seal: '#9A3412',
        },
        // All palettes for theme-aware usage
        saffron: {
          bg: '#FBF7F0',
          surface: '#FFFFFF',
          'surface-warm': '#FBF1E3',
          'surface-warmer': '#F6E6CC',
          text: '#1C1917',
          'text-muted': '#6B5E52',
          'text-faint': '#A39687',
          border: '#EAE0D2',
          'border-soft': '#F2EADC',
          primary: '#B7531A',
          'primary-deep': '#7A2E0B',
          'primary-soft': '#F8E7D2',
          accent: '#7C2D12',
          success: '#15803D',
          'success-soft': '#DCFCE7',
          info: '#1E40AF',
          warn: '#A16207',
          'warn-soft': '#FEF3C7',
          error: '#B91C1C',
          'chip-bg': '#F4EBDD',
          seal: '#9A3412',
        },
        maroon: {
          bg: '#FAF5F4',
          surface: '#FFFFFF',
          'surface-warm': '#F5E8E6',
          'surface-warmer': '#EDD4D0',
          text: '#1C1917',
          'text-muted': '#6B5959',
          'text-faint': '#A89090',
          border: '#EBDDDB',
          'border-soft': '#F2E7E5',
          primary: '#881337',
          'primary-deep': '#4C0519',
          'primary-soft': '#F4D9DF',
          accent: '#B7531A',
          success: '#15803D',
          'success-soft': '#DCFCE7',
          info: '#1E40AF',
          warn: '#A16207',
          'warn-soft': '#FEF3C7',
          error: '#B91C1C',
          'chip-bg': '#F1E2E0',
          seal: '#7F1D1D',
        },
        jade: {
          bg: '#F4F7F4',
          surface: '#FFFFFF',
          'surface-warm': '#E2EEE6',
          'surface-warmer': '#CFE2D5',
          text: '#1C1F1D',
          'text-muted': '#5C6760',
          'text-faint': '#9AA89E',
          border: '#DCE6DE',
          'border-soft': '#E8EFE9',
          primary: '#0F6E4A',
          'primary-deep': '#064E33',
          'primary-soft': '#D7EBDF',
          accent: '#B7531A',
          success: '#15803D',
          'success-soft': '#DCFCE7',
          info: '#1E40AF',
          warn: '#A16207',
          'warn-soft': '#FEF3C7',
          error: '#B91C1C',
          'chip-bg': '#E3EDE6',
          seal: '#065F46',
        },
        midnight: {
          bg: '#F5F6F9',
          surface: '#FFFFFF',
          'surface-warm': '#E6EAF2',
          'surface-warmer': '#D2D9E6',
          text: '#0F172A',
          'text-muted': '#52607A',
          'text-faint': '#94A0B5',
          border: '#DCE2EC',
          'border-soft': '#E8ECF3',
          primary: '#1E3A66',
          'primary-deep': '#0B1F40',
          'primary-soft': '#D9E1EF',
          accent: '#B7531A',
          success: '#15803D',
          'success-soft': '#DCFCE7',
          info: '#1E40AF',
          warn: '#A16207',
          'warn-soft': '#FEF3C7',
          error: '#B91C1C',
          'chip-bg': '#E2E7F1',
          seal: '#1E3A66',
        },
      },
    },
  },
  plugins: [],
};
