"""create tenants table

Revision ID: 306d9658d57a
Revises: 
Create Date: 2026-08-02 19:50:21.507586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306d9658d57a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('subdomain', sa.String(length=63), nullable=False),
    sa.Column('app_name', sa.String(length=120), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('default_language', sa.String(length=5), nullable=False),
    sa.Column('support_phone', sa.String(length=20), nullable=True),
    sa.Column('support_whatsapp', sa.String(length=20), nullable=True),
    sa.Column('launch_state', sa.Enum('draft', 'active', 'suspended', name='launchstate'), nullable=False),
    sa.Column('feature_flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_subdomain'), 'tenants', ['subdomain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_subdomain'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
