"""create profiles, photos, preferences, sub_castes, gotras

Revision ID: cc934b3f32e7
Revises: d3e7009b2eba
Create Date: 2026-08-11 23:08:47.822071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc934b3f32e7'
down_revision: Union[str, Sequence[str], None] = 'd3e7009b2eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gotras',
    sa.Column('name_hi', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gotras_tenant_id'), 'gotras', ['tenant_id'], unique=False)
    op.create_table('sub_castes',
    sa.Column('name_hi', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_castes_tenant_id'), 'sub_castes', ['tenant_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.Enum('never_married', 'divorced', 'widowed', 'awaiting_divorce', name='maritalstatus'), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('body_type', sa.Enum('slim', 'average', 'heavy', 'athletic', name='bodytype'), nullable=True),
    sa.Column('complexion', sa.Enum('fair', 'wheatish', 'dark', name='complexion'), nullable=True),
    sa.Column('has_physical_challenge', sa.Boolean(), nullable=False),
    sa.Column('sub_caste', sa.String(length=100), nullable=True),
    sa.Column('gotra', sa.String(length=100), nullable=True),
    sa.Column('same_gotra_acceptable', sa.Boolean(), nullable=False),
    sa.Column('mother_tongue', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('district', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('residing_since', sa.Integer(), nullable=True),
    sa.Column('is_native_place', sa.Boolean(), nullable=False),
    sa.Column('native_state', sa.String(length=60), nullable=True),
    sa.Column('native_district', sa.String(length=60), nullable=True),
    sa.Column('native_village_or_town', sa.String(length=100), nullable=True),
    sa.Column('family_still_there', sa.Boolean(), nullable=True),
    sa.Column('owns_land', sa.Enum('yes', 'no', 'skip', name='ownsland'), nullable=True),
    sa.Column('highest_qualification', sa.String(length=100), nullable=True),
    sa.Column('specialisation', sa.String(length=100), nullable=True),
    sa.Column('college_university', sa.String(length=150), nullable=True),
    sa.Column('year_of_passing', sa.Integer(), nullable=True),
    sa.Column('currently_studying', sa.Boolean(), nullable=False),
    sa.Column('profession_category', sa.Enum('government', 'private', 'business', 'agriculture', 'professional', 'student', name='professioncategory'), nullable=True),
    sa.Column('specific_role', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('work_location', sa.String(length=100), nullable=True),
    sa.Column('annual_income', sa.Integer(), nullable=True),
    sa.Column('income_verify_requested', sa.Boolean(), nullable=False),
    sa.Column('diet', sa.Enum('veg', 'egg', 'non_veg', 'jain', name='diet'), nullable=True),
    sa.Column('drinking', sa.Enum('never', 'occasionally', 'socially', name='drinking'), nullable=True),
    sa.Column('smoking', sa.Enum('never', 'occasionally', name='smoking'), nullable=True),
    sa.Column('hobbies', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('languages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('father_name', sa.String(length=150), nullable=True),
    sa.Column('father_occupation', sa.String(length=100), nullable=True),
    sa.Column('mother_name', sa.String(length=150), nullable=True),
    sa.Column('mother_occupation', sa.String(length=100), nullable=True),
    sa.Column('brothers_count', sa.Integer(), nullable=False),
    sa.Column('brothers_married_count', sa.Integer(), nullable=False),
    sa.Column('sisters_count', sa.Integer(), nullable=False),
    sa.Column('sisters_married_count', sa.Integer(), nullable=False),
    sa.Column('family_type', sa.Enum('joint', 'nuclear', name='familytype'), nullable=True),
    sa.Column('family_values', sa.Enum('orthodox', 'traditional', 'moderate', 'liberal', name='familyvalues'), nullable=True),
    sa.Column('believes_in_kundli_matching', sa.Boolean(), nullable=False),
    sa.Column('time_of_birth', sa.Time(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=150), nullable=True),
    sa.Column('manglik_status', sa.String(length=30), nullable=True),
    sa.Column('nakshatra', sa.String(length=50), nullable=True),
    sa.Column('rashi', sa.String(length=50), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('partner_expectation_summary', sa.Text(), nullable=True),
    sa.Column('photo_visibility', sa.Enum('all', 'premium_only', 'on_request', name='photovisibility'), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_profiles_user_id')
    )
    op.create_index('ix_profiles_tenant_gender_dob', 'profiles', ['tenant_id', 'gender', 'date_of_birth'], unique=False)
    op.create_index(op.f('ix_profiles_tenant_id'), 'profiles', ['tenant_id'], unique=False)
    op.create_index('ix_profiles_tenant_subcaste_district', 'profiles', ['tenant_id', 'sub_caste', 'district'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_table('profile_photos',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('url_thumb', sa.Text(), nullable=False),
    sa.Column('url_medium', sa.Text(), nullable=False),
    sa.Column('url_full', sa.Text(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_photos_profile_id'), 'profile_photos', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_photos_tenant_id'), 'profile_photos', ['tenant_id'], unique=False)
    op.create_table('profile_preferences',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('partner_age_min', sa.Integer(), nullable=True),
    sa.Column('partner_age_max', sa.Integer(), nullable=True),
    sa.Column('partner_height_min', sa.Integer(), nullable=True),
    sa.Column('partner_height_max', sa.Integer(), nullable=True),
    sa.Column('partner_marital_status', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('partner_manglik', sa.Enum('no_only', 'doesnt_matter', 'anshik_ok', name='partnermanglik'), nullable=False),
    sa.Column('partner_diet', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('partner_sub_castes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('partner_same_gotra_acceptable', sa.Boolean(), nullable=False),
    sa.Column('partner_other_castes_acceptable', sa.Boolean(), nullable=False),
    sa.Column('partner_states', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('partner_languages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('partner_professions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('partner_min_education', sa.String(length=100), nullable=True),
    sa.Column('partner_min_income', sa.Integer(), nullable=True),
    sa.Column('partner_want_working_professional', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='uq_profile_preferences_profile_id')
    )
    op.create_index(op.f('ix_profile_preferences_profile_id'), 'profile_preferences', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_preferences_tenant_id'), 'profile_preferences', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_preferences_tenant_id'), table_name='profile_preferences')
    op.drop_index(op.f('ix_profile_preferences_profile_id'), table_name='profile_preferences')
    op.drop_table('profile_preferences')
    op.drop_index(op.f('ix_profile_photos_tenant_id'), table_name='profile_photos')
    op.drop_index(op.f('ix_profile_photos_profile_id'), table_name='profile_photos')
    op.drop_table('profile_photos')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index('ix_profiles_tenant_subcaste_district', table_name='profiles')
    op.drop_index(op.f('ix_profiles_tenant_id'), table_name='profiles')
    op.drop_index('ix_profiles_tenant_gender_dob', table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_sub_castes_tenant_id'), table_name='sub_castes')
    op.drop_table('sub_castes')
    op.drop_index(op.f('ix_gotras_tenant_id'), table_name='gotras')
    op.drop_table('gotras')
    # ### end Alembic commands ###
