"""create matches table

Revision ID: d7dde2c6553b
Revises: cc934b3f32e7
Create Date: 2026-08-16 17:13:49.005298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7dde2c6553b'
down_revision: Union[str, Sequence[str], None] = 'cc934b3f32e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('user_a_id', sa.String(length=36), nullable=False),
    sa.Column('user_b_id', sa.String(length=36), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('viewed_by_a', sa.Boolean(), nullable=False),
    sa.Column('viewed_by_b', sa.Boolean(), nullable=False),
    sa.Column('shortlisted_by_a', sa.Boolean(), nullable=False),
    sa.Column('shortlisted_by_b', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='uq_matches_user_pair')
    )
    op.create_index(op.f('ix_matches_tenant_id'), 'matches', ['tenant_id'], unique=False)
    op.create_index('ix_matches_tenant_user_a_score', 'matches', ['tenant_id', 'user_a_id', 'match_score'], unique=False)
    op.create_index('ix_matches_tenant_user_b_score', 'matches', ['tenant_id', 'user_b_id', 'match_score'], unique=False)
    op.create_index(op.f('ix_matches_user_a_id'), 'matches', ['user_a_id'], unique=False)
    op.create_index(op.f('ix_matches_user_b_id'), 'matches', ['user_b_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_user_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_user_a_id'), table_name='matches')
    op.drop_index('ix_matches_tenant_user_b_score', table_name='matches')
    op.drop_index('ix_matches_tenant_user_a_score', table_name='matches')
    op.drop_index(op.f('ix_matches_tenant_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
